In [2]:
import pandas as pd
import cufflinks as cf
import sqlite3
import numpy as np

cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)

con = sqlite3.connect("portal_mammals (1).sqlite")
con.close
df_surveys = pd.read_sql_query("SELECT * from surveys", con)
df_species = pd.read_sql_query("SELECT * from species", con)
df_plots = pd.read_sql_query("SELECT * from plots",con)

sex_hf = pd.read_sql_query('''SELECT s.genus, s.taxa, y.sex, p.plot_type, y.hindfoot_length
                                    FROM species s, surveys y, plots p
                                    WHERE s.species_id = y.species_id AND p.plot_id = y.plot_id''', con)

display(sex_hf)

sex_hf=sex_hf.dropna(subset=['sex','hindfoot_length'])
display(sex_hf)


sex_hf = sex_hf[['genus','sex','plot_type','hindfoot_length']]
sex_hf['hindfoot_length']=sex_hf['hindfoot_length'].astype(int)
sex_hf = sex_hf[0:10]
display(sex_hf)

# new_con = sqlite3.connect("new_species.sqlite3")
# new_cur = new_con.cursor()

# new_cur.execute('''CREATE TABLE IF NOT EXISTS species(
#                     id integer primary key autoincrement,
#                     nick text,
#                     first_name text,
#                     last_name text,
#                     phone int
# ) ''')

# for ix, row in sex_hf.iterrows():
#     new_cur.execute(''' INSERT INTO species
#                         (nick, first_name,last_name,phone) VALUES (?,?,?,?);
#                         ''',(row["genus"],row["sex"],row["plot_type"],row["hindfoot_length"]))
# new_con.commit()

# new_cur.execute("SELECT * FROM species")
# data = new_cur.fetchall()
# for d in data:
#     print(d)
# new_con.close()
new_con = sqlite3.connect("new_species_names.sqlite3")
new_cur = new_con.cursor()

new_cur.execute('''CREATE TABLE IF NOT EXISTS species(
                    id integer primary key autoincrement,
                    genus text,
                    sex text,
                    plot_type text,
                    hindfoot_length int
) ''')

for ix, row in sex_hf.iterrows():
    new_cur.execute(''' INSERT INTO species
                        (genus, sex,plot_type,hindfoot_length) VALUES (?,?,?,?);
                        ''',(row["genus"],row["sex"],row["plot_type"],row["hindfoot_length"]))
new_con.commit()

new_cur.execute("SELECT * FROM species")
data = new_cur.fetchall()
for d in data:
    print(d)
new_con.close()